#!/usr/bin/env python3
"""Generate specialized ForUtil decoders, one per bit width, like Lucene's gen_ForUtil.py.

The layout is the one written by `forutil::encode` (a port of Lucene104 ForUtil#encode):
values are collapsed into 8/16/32-bit lanes of u32 words, the first floor(P/B) "shifts" fill
B*8 words, and the remaining values are an MSB-first bit stream over the low r bits of those
words. Each generated decoder unpacks straight into the expanded 256-value output.

Usage: python3 scripts/gen_forutil.py > src/codec/forutil_gen.rs
"""

BLOCK = 256


def lane_mask(p, b):
    m = (1 << b) - 1 if b < 32 else 0xFFFFFFFF
    if p == 8:
        m |= m << 8
        m |= m << 16
    elif p == 16:
        m |= m << 16
    return m & 0xFFFFFFFF


def put(p, word, expr):
    """Write the lanes of collapsed word index `word` to their expanded positions."""
    if p == 32:
        return [f"    ints[{word}] = {expr};"]
    lines = [f"    let x = {expr};"]
    if p == 16:
        lines.append(f"    ints[{word}] = x >> 16;")
        lines.append(f"    ints[{128 + word}] = x & 0xFFFF;")
    else:
        for k, sh in enumerate((24, 16, 8, 0)):
            e = f"x >> {sh}" if sh == 24 else (f"(x >> {sh}) & 0xFF" if sh else "x & 0xFF")
            lines.append(f"    ints[{64 * k + word}] = {e};")
    return ["    {"] + ["    " + l for l in lines] + ["    }"]


def gen(b):
    p = 8 if b <= 8 else 16 if b <= 16 else 32
    num_ints = BLOCK * p // 32
    nips = b * 8
    out = [f"#[inline(always)]", f"fn decode{b}(src: &[u8], ints: &mut [u32; 256]) {{"]
    out.append(f"    let src: &[u8; {nips * 4}] = src[..{nips * 4}].try_into().unwrap();")
    out.append(f"    let mut t = [0u32; {nips}];")
    out.append(f"    for (w, c) in t.iter_mut().zip(src.chunks_exact(4)) {{ *w = u32::from_le_bytes(c.try_into().unwrap()); }}")
    idx = 0
    shift = p - b
    mask = lane_mask(p, b)
    while shift >= 0:
        # vectorizable loop over the nips words for this shift
        if p == 32:
            out.append(f"    for i in 0..{nips} {{ ints[{idx} + i] = (t[i] >> {shift}) & {mask:#x}; }}")
        elif p == 16:
            out.append(f"    for i in 0..{nips} {{ let x = (t[i] >> {shift}) & {mask:#x}; ints[{idx} + i] = x >> 16; ints[{128 + idx} + i] = x & 0xFFFF; }}")
        else:
            out.append(
                f"    for i in 0..{nips} {{ let x = (t[i] >> {shift}) & {mask:#x}; "
                f"ints[{idx} + i] = x >> 24; ints[{64 + idx} + i] = (x >> 16) & 0xFF; "
                f"ints[{128 + idx} + i] = (x >> 8) & 0xFF; ints[{192 + idx} + i] = x & 0xFF; }}"
            )
        idx += nips
        shift -= b
    r = shift + b
    # remaining values: MSB-first stream of r-bit chunks (chunk j = low r bits of t[j])
    v = 0
    while idx < num_ints:
        start, end = v * b, (v + 1) * b
        parts = []
        pos = start
        while pos < end:
            j = pos // r
            chunk_end = (j + 1) * r
            take = min(end, chunk_end) - pos
            # bits [pos, pos+take) of the stream = bits of chunk j from the top
            down = chunk_end - (pos + take)
            left = end - (pos + take)
            e = f"t[{j}]"
            if down:
                e = f"({e} >> {down})"
            e = f"({e} & {lane_mask(p, take):#x})"
            if left:
                e = f"({e} << {left})"
            parts.append(e)
            pos += take
        out += put(p, idx, " | ".join(parts))
        idx += 1
        v += 1
    out.append("}")
    return "\n".join(out)


print("// @generated by scripts/gen_forutil.py. DO NOT EDIT.")
print("// Specialized decoders for the ForUtil layout (port of Lucene104 ForUtil).")
print("#![allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::restriction)]")
print()
for b in range(1, 33):
    print(gen(b))
    print()
print("/// Decode 256 values of `bpv` bits from the front of `src` into `ints`.")
print("#[inline]")
print("pub fn decode(bpv: u32, src: &[u8], ints: &mut [u32; 256]) {")
print("    match bpv {")
for b in range(1, 33):
    print(f"        {b} => decode{b}(src, ints),")
print('        _ => panic!("invalid bits per value: {bpv}"),')
print("    }")
print("}")
